"""Reads and writes recovered from a Spark physical plan.

The fixtures here are **real `EXPLAIN FORMATTED` output from PySpark 4**, with
the local `file:` paths swapped for the `abfss://` OneLake ones Fabric would
render. That matters: the formatted plan is not a documented contract, and a
parser written against a guess at it is a parser written against nothing. Every
shape below was generated by running the statement and copying what Spark said.

Three shapes, and they render very differently — which is the whole reason this
module needs tests rather than a regex:

  * an INSERT compiles to a PHYSICAL plan: `Scan parquet` nodes with a
    `Location:` bracket, and a write command carrying its path in `Arguments:`;
  * a CTAS compiles to a COMMAND wrapping an unresolved LOGICAL plan: no `Scan`
    node, no `Location:` anywhere, and both the target and the sources named
    only as backticked catalog identifiers;
  * a plain SELECT has sources and no target at all.
"""

from __future__ import annotations

from app.fabric.plans import scan_plan
from app.sandbox._refs import make_ref

WS, LH = "Finance", "Bronze"
ORDERS = make_ref("orders", LH, WS)
CUSTOMERS = make_ref("customers", LH, WS)
GOLD = make_ref("g1", LH, WS)

ABFSS = f"abfss://{WS}@onelake.dfs.fabric.microsoft.com/{LH}.Lakehouse/Tables"


def scan(plan):
    return scan_plan(plan, workspace=WS, lakehouse=LH)


# --- a physical plan: INSERT INTO ------------------------------------------

INSERT_PLAN = f"""== Physical Plan ==
AdaptiveSparkPlan (5)
+- Execute InsertIntoHadoopFsRelationCommand (5)
   +- WriteFiles (4)
      +- * Project (3)
         +- * ColumnarToRow (2)
            +- Scan parquet spark_catalog.{LH}.orders (1)


(1) Scan parquet spark_catalog.{LH}.orders
Output [1]: [cust_id#6L]
Batched: true
Location: InMemoryFileIndex [{ABFSS}/orders]
ReadSchema: struct<cust_id:bigint>

(2) ColumnarToRow [codegen id : 1]
Input [1]: [cust_id#6L]

(3) Project [codegen id : 1]
Output [2]: [cust_id#6L, x AS region#16]
Input [1]: [cust_id#6L]

(4) WriteFiles
Input [2]: [cust_id#6L, region#16]

(5) Execute InsertIntoHadoopFsRelationCommand
Input: []
Arguments: {ABFSS}/customers, false, Parquet, [path={ABFSS}/customers], Append, \
`spark_catalog`.`{LH}`.`customers`, \
org.apache.spark.sql.execution.datasources.InMemoryFileIndex({ABFSS}/customers), [cust_id, region]
"""


def test_an_insert_resolves_its_source_and_its_target():
    result = scan(INSERT_PLAN)
    assert result.reads == {ORDERS}
    assert result.writes == {CUSTOMERS}


def test_a_path_and_a_catalog_name_for_one_table_do_not_become_two():
    """The write node names its target BOTH ways — as an `abfss://` path and as
    `` `spark_catalog`.`Bronze`.`customers` ``.

    The path carries the workspace and the identifier does not, so resolving both
    would yield two refs for one table: the real one, and one defaulted into the
    notebook's own workspace. The path wins, and a table keeps a single identity.
    """
    result = scan(INSERT_PLAN)
    assert len(result.writes) == 1
    assert result.unrecognised == set()


# --- a command wrapping a logical plan: CTAS -------------------------------

CTAS_PLAN = f"""== Physical Plan ==
Execute CreateDataSourceTableAsSelectCommand (1)
   +- CreateDataSourceTableAsSelectCommand (2)
         +- Project (10)
            +- Join (9)
               :- SubqueryAlias (5)
               :  +- SubqueryAlias (4)
               :     +- LogicalRelation (3)
               +- SubqueryAlias (8)
                  +- SubqueryAlias (7)
                     +- LogicalRelation (6)


(1) Execute CreateDataSourceTableAsSelectCommand
Output: []

(2) CreateDataSourceTableAsSelectCommand
Arguments: `spark_catalog`.`{LH}`.`g1`, ErrorIfExists, [id, region]

(3) LogicalRelation
Arguments: parquet, [id#4L, amount#5, cust_id#6L], `spark_catalog`.`{LH}`.`orders`, false

(4) SubqueryAlias
Arguments: spark_catalog.{LH}.orders

(5) SubqueryAlias
Arguments: o

(6) LogicalRelation
Arguments: parquet, [cust_id#7L, region#8], `spark_catalog`.`{LH}`.`customers`, false

(7) SubqueryAlias
Arguments: spark_catalog.{LH}.customers

(8) SubqueryAlias
Arguments: c

(9) Join
Arguments: Inner, (cust_id#6L = cust_id#7L)

(10) Project
Arguments: [id#4L, region#8]
"""


def test_a_ctas_resolves_through_the_logical_plan():
    """The shape a medallion notebook is actually written in, and the one with
    no `Scan` node and no `Location:` anywhere to key off."""
    result = scan(CTAS_PLAN)
    assert result.writes == {GOLD}
    assert result.reads == {ORDERS, CUSTOMERS}


def test_the_execute_wrapper_is_not_reported_as_unparsed():
    """`Execute <Command>` renders with a bare `Output: []` and wraps the node
    that holds the detail. Flagging it would warn on every CTAS ever run."""
    assert scan(CTAS_PLAN).unrecognised == set()


def test_spark_own_catalog_never_becomes_a_workspace():
    """`spark_catalog` is an engine detail, not a lakehouse."""
    for ref in scan(CTAS_PLAN).reads | scan(CTAS_PLAN).writes:
        assert "spark_catalog" not in ref


# --- reads with no write ----------------------------------------------------

SELECT_PLAN = f"""== Physical Plan ==
AdaptiveSparkPlan (3)
+- Project (3)
   +- Scan parquet  (1)


(1) Scan parquet
Output [2]: [id#5L, cust_id#7L]
Batched: true
Location: PreparedDeltaFileIndex [{ABFSS}/orders]
ReadSchema: struct<id:bigint,cust_id:bigint>

(3) Project
Output [1]: [id#5L]
Input [2]: [id#5L, cust_id#7L]
"""


def test_a_read_only_plan_reports_reads_and_no_writes():
    result = scan(SELECT_PLAN)
    assert result.reads == {ORDERS}
    assert result.writes == set()


def test_a_table_read_and_written_in_one_plan_is_a_write():
    """The same rule the sandbox applies, so the two answers stay comparable."""
    plan = INSERT_PLAN.replace(f"{ABFSS}/customers", f"{ABFSS}/orders")
    result = scan(plan)
    assert result.writes == {ORDERS}
    assert ORDERS not in result.reads


# --- degradation ------------------------------------------------------------

def test_a_multi_path_location_yields_every_table():
    plan = f"""== Physical Plan ==
Scan parquet (1)

(1) Scan parquet
Location: InMemoryFileIndex [{ABFSS}/orders, {ABFSS}/customers]
ReadSchema: struct<id:bigint>
"""
    assert scan(plan).reads == {ORDERS, CUSTOMERS}


def test_a_truncated_path_list_does_not_invent_a_table():
    """Spark elides a long list with `...`; it names nothing and must not be
    resolved into a table called `...`."""
    plan = f"""== Physical Plan ==
Scan parquet (1)

(1) Scan parquet
Location: InMemoryFileIndex(9 paths) [{ABFSS}/orders, ...]
"""
    assert scan(plan).reads == {ORDERS}


def test_a_maintenance_command_is_not_a_write():
    """OPTIMIZE and VACUUM touch a table without moving data into it; counting
    them would put an edge in the graph for a compaction job."""
    plan = f"""== Physical Plan ==
Execute OptimizeTableCommand (1)

(1) Execute OptimizeTableCommand
Arguments: `spark_catalog`.`{LH}`.`orders`, [], false
"""
    result = scan(plan)
    assert result.writes == set()
    assert result.reads == set()


def test_an_in_memory_scan_names_no_source():
    """`LocalTableScan` reads from the driver, not from storage. It is not a gap
    to be reported — there is genuinely nothing there."""
    plan = """== Physical Plan ==
LocalTableScan (1)

(1) LocalTableScan
Output [2]: [CommonName#7, ScientificName#8]
Arguments: [CommonName#7, ScientificName#8]
"""
    result = scan(plan)
    assert (result.reads, result.writes, result.unrecognised) == (set(), set(), set())


def test_an_unreadable_plan_degrades_to_nothing():
    for junk in ("", "   ", "== Physical Plan ==\n", "not a plan at all"):
        result = scan(junk)
        assert (result.reads, result.writes) == (set(), set())


def test_an_unknown_write_node_is_reported_rather_than_silently_dropped():
    """A plan that yields nothing must be distinguishable from a plan that moved
    nothing — the same reason `Coverage` exists on the sandbox side."""
    plan = """== Physical Plan ==
Execute SaveIntoDataSourceCommand (1)

(1) Execute SaveIntoDataSourceCommand
Arguments: com.example.SomeSink, Map(mystery -> yes), Append
"""
    assert "Execute SaveIntoDataSourceCommand" in scan(plan).unrecognised


# --- non-formatted plans ----------------------------------------------------

def test_a_simple_mode_plan_still_yields_tables():
    """`spark.sql.ui.explainMode` is configurable, so `formatted` is the default
    rather than a guarantee. One-line operators must still resolve."""
    plan = f"""== Physical Plan ==
Execute InsertIntoHadoopFsRelationCommand {ABFSS}/customers, false, Parquet, Append
+- *(1) Project [cust_id#6L]
   +- *(1) FileScan parquet [cust_id#6L] Batched: true, Location: InMemoryFileIndex[{ABFSS}/orders], ReadSchema: struct<cust_id:bigint>
"""
    result = scan(plan)
    assert result.writes == {CUSTOMERS}
    assert result.reads == {ORDERS}


# --- workspace resolution ---------------------------------------------------

def test_a_cross_workspace_path_keeps_its_own_workspace():
    """A notebook reaching into another workspace addresses it by path, and that
    path's workspace must win over the notebook's own."""
    plan = """== Physical Plan ==
Scan parquet (1)

(1) Scan parquet
Location: InMemoryFileIndex [abfss://Marketing@onelake.dfs.fabric.microsoft.com/Gold.Lakehouse/Tables/orders]
"""
    assert scan(plan).reads == {make_ref("orders", "Gold", "Marketing")}


def test_guids_in_a_path_resolve_through_the_name_map():
    ws = "11111111-1111-1111-1111-111111111111"
    lh = "22222222-2222-2222-2222-222222222222"
    plan = f"""== Physical Plan ==
Scan parquet (1)

(1) Scan parquet
Location: InMemoryFileIndex [abfss://{ws}@onelake.dfs.fabric.microsoft.com/{lh}/Tables/orders]
"""
    result = scan_plan(plan, WS, LH, {ws: "Marketing", lh: "Gold"})
    assert result.reads == {make_ref("orders", "Gold", "Marketing")}
