/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphRouteRouteImport } from './routes/graph/route'
import { Route as LineageRouteRouteImport } from './routes/lineage/route'
import { Route as ProductsRouteRouteImport } from './routes/products/route'
import { Route as PurviewRouteRouteImport } from './routes/purview/route'
import { Route as GraphIndexRouteImport } from './routes/graph/index'
import { Route as ModelIndexRouteImport } from './routes/model.index'
import { Route as ModelSplatRouteImport } from './routes/model.$'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ProductsDomainsRouteImport } from './routes/products/domains'
import { Route as ProductsNewRouteImport } from './routes/products/new'
import { Route as ProductsRequestsRouteImport } from './routes/products/requests'
import { Route as PurviewDataProductsRouteImport } from './routes/purview/data-products'
import { Route as PurviewDefinitionsRouteImport } from './routes/purview/definitions'
import { Route as PurviewPushRouteImport } from './routes/purview/push'
import { Route as GraphWorkspaceIndexRouteImport } from './routes/graph/$workspace.index'
import { Route as GraphWorkspaceLakehouseIndexRouteImport } from './routes/graph/$workspace.$lakehouse.index'
import { Route as GraphWorkspaceLakehouseTableRouteImport } from './routes/graph/$workspace.$lakehouse.$table'
import { Route as LineageWorkspaceLakehouseTableRouteImport } from './routes/lineage/$workspace.$lakehouse.$table'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRouteRoute = GraphRouteRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const LineageRouteRoute = LineageRouteRouteImport.update({
  id: '/lineage',
  path: '/lineage',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRouteRoute = ProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PurviewRouteRoute = PurviewRouteRouteImport.update({
  id: '/purview',
  path: '/purview',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphIndexRoute = GraphIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GraphRouteRoute,
} as any)
const ModelIndexRoute = ModelIndexRouteImport.update({
  id: '/model/',
  path: '/model/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelSplatRoute = ModelSplatRouteImport.update({
  id: '/model/$',
  path: '/model/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ProductsDomainsRoute = ProductsDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ProductsRequestsRoute = ProductsRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const PurviewDataProductsRoute = PurviewDataProductsRouteImport.update({
  id: '/data-products',
  path: '/data-products',
  getParentRoute: () => PurviewRouteRoute,
} as any)
const PurviewDefinitionsRoute = PurviewDefinitionsRouteImport.update({
  id: '/definitions',
  path: '/definitions',
  getParentRoute: () => PurviewRouteRoute,
} as any)
const PurviewPushRoute = PurviewPushRouteImport.update({
  id: '/push',
  path: '/push',
  getParentRoute: () => PurviewRouteRoute,
} as any)
const GraphWorkspaceIndexRoute = GraphWorkspaceIndexRouteImport.update({
  id: '/$workspace/',
  path: '/$workspace/',
  getParentRoute: () => GraphRouteRoute,
} as any)
const GraphWorkspaceLakehouseIndexRoute =
  GraphWorkspaceLakehouseIndexRouteImport.update({
    id: '/$workspace/$lakehouse/',
    path: '/$workspace/$lakehouse/',
    getParentRoute: () => GraphRouteRoute,
  } as any)
const GraphWorkspaceLakehouseTableRoute =
  GraphWorkspaceLakehouseTableRouteImport.update({
    id: '/$workspace/$lakehouse/$table',
    path: '/$workspace/$lakehouse/$table',
    getParentRoute: () => GraphRouteRoute,
  } as any)
const LineageWorkspaceLakehouseTableRoute =
  LineageWorkspaceLakehouseTableRouteImport.update({
    id: '/$workspace/$lakehouse/$table',
    path: '/$workspace/$lakehouse/$table',
    getParentRoute: () => LineageRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph': typeof GraphRouteRouteWithChildren
  '/lineage': typeof LineageRouteRouteWithChildren
  '/products': typeof ProductsRouteRouteWithChildren
  '/purview': typeof PurviewRouteRouteWithChildren
  '/model/$': typeof ModelSplatRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/domains': typeof ProductsDomainsRoute
  '/products/new': typeof ProductsNewRoute
  '/products/requests': typeof ProductsRequestsRoute
  '/purview/data-products': typeof PurviewDataProductsRoute
  '/purview/definitions': typeof PurviewDefinitionsRoute
  '/purview/push': typeof PurviewPushRoute
  '/graph/': typeof GraphIndexRoute
  '/model/': typeof ModelIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/graph/$workspace/': typeof GraphWorkspaceIndexRoute
  '/graph/$workspace/$lakehouse/$table': typeof GraphWorkspaceLakehouseTableRoute
  '/lineage/$workspace/$lakehouse/$table': typeof LineageWorkspaceLakehouseTableRoute
  '/graph/$workspace/$lakehouse/': typeof GraphWorkspaceLakehouseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lineage': typeof LineageRouteRouteWithChildren
  '/purview': typeof PurviewRouteRouteWithChildren
  '/model/$': typeof ModelSplatRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/domains': typeof ProductsDomainsRoute
  '/products/new': typeof ProductsNewRoute
  '/products/requests': typeof ProductsRequestsRoute
  '/purview/data-products': typeof PurviewDataProductsRoute
  '/purview/definitions': typeof PurviewDefinitionsRoute
  '/purview/push': typeof PurviewPushRoute
  '/graph': typeof GraphIndexRoute
  '/model': typeof ModelIndexRoute
  '/products': typeof ProductsIndexRoute
  '/graph/$workspace': typeof GraphWorkspaceIndexRoute
  '/graph/$workspace/$lakehouse/$table': typeof GraphWorkspaceLakehouseTableRoute
  '/lineage/$workspace/$lakehouse/$table': typeof LineageWorkspaceLakehouseTableRoute
  '/graph/$workspace/$lakehouse': typeof GraphWorkspaceLakehouseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graph': typeof GraphRouteRouteWithChildren
  '/lineage': typeof LineageRouteRouteWithChildren
  '/products': typeof ProductsRouteRouteWithChildren
  '/purview': typeof PurviewRouteRouteWithChildren
  '/model/$': typeof ModelSplatRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/domains': typeof ProductsDomainsRoute
  '/products/new': typeof ProductsNewRoute
  '/products/requests': typeof ProductsRequestsRoute
  '/purview/data-products': typeof PurviewDataProductsRoute
  '/purview/definitions': typeof PurviewDefinitionsRoute
  '/purview/push': typeof PurviewPushRoute
  '/graph/': typeof GraphIndexRoute
  '/model/': typeof ModelIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/graph/$workspace/': typeof GraphWorkspaceIndexRoute
  '/graph/$workspace/$lakehouse/$table': typeof GraphWorkspaceLakehouseTableRoute
  '/lineage/$workspace/$lakehouse/$table': typeof LineageWorkspaceLakehouseTableRoute
  '/graph/$workspace/$lakehouse/': typeof GraphWorkspaceLakehouseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/graph'
    | '/lineage'
    | '/products'
    | '/purview'
    | '/model/$'
    | '/products/$productId'
    | '/products/domains'
    | '/products/new'
    | '/products/requests'
    | '/purview/data-products'
    | '/purview/definitions'
    | '/purview/push'
    | '/graph/'
    | '/model/'
    | '/products/'
    | '/graph/$workspace/'
    | '/graph/$workspace/$lakehouse/$table'
    | '/lineage/$workspace/$lakehouse/$table'
    | '/graph/$workspace/$lakehouse/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lineage'
    | '/purview'
    | '/model/$'
    | '/products/$productId'
    | '/products/domains'
    | '/products/new'
    | '/products/requests'
    | '/purview/data-products'
    | '/purview/definitions'
    | '/purview/push'
    | '/graph'
    | '/model'
    | '/products'
    | '/graph/$workspace'
    | '/graph/$workspace/$lakehouse/$table'
    | '/lineage/$workspace/$lakehouse/$table'
    | '/graph/$workspace/$lakehouse'
  id:
    | '__root__'
    | '/'
    | '/graph'
    | '/lineage'
    | '/products'
    | '/purview'
    | '/model/$'
    | '/products/$productId'
    | '/products/domains'
    | '/products/new'
    | '/products/requests'
    | '/purview/data-products'
    | '/purview/definitions'
    | '/purview/push'
    | '/graph/'
    | '/model/'
    | '/products/'
    | '/graph/$workspace/'
    | '/graph/$workspace/$lakehouse/$table'
    | '/lineage/$workspace/$lakehouse/$table'
    | '/graph/$workspace/$lakehouse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphRouteRoute: typeof GraphRouteRouteWithChildren
  LineageRouteRoute: typeof LineageRouteRouteWithChildren
  ProductsRouteRoute: typeof ProductsRouteRouteWithChildren
  PurviewRouteRoute: typeof PurviewRouteRouteWithChildren
  ModelSplatRoute: typeof ModelSplatRoute
  ModelIndexRoute: typeof ModelIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineage': {
      id: '/lineage'
      path: '/lineage'
      fullPath: '/lineage'
      preLoaderRoute: typeof LineageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purview': {
      id: '/purview'
      path: '/purview'
      fullPath: '/purview'
      preLoaderRoute: typeof PurviewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph/': {
      id: '/graph/'
      path: '/'
      fullPath: '/graph/'
      preLoaderRoute: typeof GraphIndexRouteImport
      parentRoute: typeof GraphRouteRoute
    }
    '/model/': {
      id: '/model/'
      path: '/model'
      fullPath: '/model/'
      preLoaderRoute: typeof ModelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model/$': {
      id: '/model/$'
      path: '/model/$'
      fullPath: '/model/$'
      preLoaderRoute: typeof ModelSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/products/domains': {
      id: '/products/domains'
      path: '/domains'
      fullPath: '/products/domains'
      preLoaderRoute: typeof ProductsDomainsRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/products/new': {
      id: '/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/products/requests': {
      id: '/products/requests'
      path: '/requests'
      fullPath: '/products/requests'
      preLoaderRoute: typeof ProductsRequestsRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/purview/data-products': {
      id: '/purview/data-products'
      path: '/data-products'
      fullPath: '/purview/data-products'
      preLoaderRoute: typeof PurviewDataProductsRouteImport
      parentRoute: typeof PurviewRouteRoute
    }
    '/purview/definitions': {
      id: '/purview/definitions'
      path: '/definitions'
      fullPath: '/purview/definitions'
      preLoaderRoute: typeof PurviewDefinitionsRouteImport
      parentRoute: typeof PurviewRouteRoute
    }
    '/purview/push': {
      id: '/purview/push'
      path: '/push'
      fullPath: '/purview/push'
      preLoaderRoute: typeof PurviewPushRouteImport
      parentRoute: typeof PurviewRouteRoute
    }
    '/graph/$workspace/': {
      id: '/graph/$workspace/'
      path: '/$workspace'
      fullPath: '/graph/$workspace/'
      preLoaderRoute: typeof GraphWorkspaceIndexRouteImport
      parentRoute: typeof GraphRouteRoute
    }
    '/graph/$workspace/$lakehouse/': {
      id: '/graph/$workspace/$lakehouse/'
      path: '/$workspace/$lakehouse'
      fullPath: '/graph/$workspace/$lakehouse/'
      preLoaderRoute: typeof GraphWorkspaceLakehouseIndexRouteImport
      parentRoute: typeof GraphRouteRoute
    }
    '/graph/$workspace/$lakehouse/$table': {
      id: '/graph/$workspace/$lakehouse/$table'
      path: '/$workspace/$lakehouse/$table'
      fullPath: '/graph/$workspace/$lakehouse/$table'
      preLoaderRoute: typeof GraphWorkspaceLakehouseTableRouteImport
      parentRoute: typeof GraphRouteRoute
    }
    '/lineage/$workspace/$lakehouse/$table': {
      id: '/lineage/$workspace/$lakehouse/$table'
      path: '/$workspace/$lakehouse/$table'
      fullPath: '/lineage/$workspace/$lakehouse/$table'
      preLoaderRoute: typeof LineageWorkspaceLakehouseTableRouteImport
      parentRoute: typeof LineageRouteRoute
    }
  }
}

interface GraphRouteRouteChildren {
  GraphIndexRoute: typeof GraphIndexRoute
  GraphWorkspaceIndexRoute: typeof GraphWorkspaceIndexRoute
  GraphWorkspaceLakehouseTableRoute: typeof GraphWorkspaceLakehouseTableRoute
  GraphWorkspaceLakehouseIndexRoute: typeof GraphWorkspaceLakehouseIndexRoute
}

const GraphRouteRouteChildren: GraphRouteRouteChildren = {
  GraphIndexRoute: GraphIndexRoute,
  GraphWorkspaceIndexRoute: GraphWorkspaceIndexRoute,
  GraphWorkspaceLakehouseTableRoute: GraphWorkspaceLakehouseTableRoute,
  GraphWorkspaceLakehouseIndexRoute: GraphWorkspaceLakehouseIndexRoute,
}

const GraphRouteRouteWithChildren = GraphRouteRoute._addFileChildren(
  GraphRouteRouteChildren,
)

interface LineageRouteRouteChildren {
  LineageWorkspaceLakehouseTableRoute: typeof LineageWorkspaceLakehouseTableRoute
}

const LineageRouteRouteChildren: LineageRouteRouteChildren = {
  LineageWorkspaceLakehouseTableRoute: LineageWorkspaceLakehouseTableRoute,
}

const LineageRouteRouteWithChildren = LineageRouteRoute._addFileChildren(
  LineageRouteRouteChildren,
)

interface ProductsRouteRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsDomainsRoute: typeof ProductsDomainsRoute
  ProductsNewRoute: typeof ProductsNewRoute
  ProductsRequestsRoute: typeof ProductsRequestsRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteRouteChildren: ProductsRouteRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsDomainsRoute: ProductsDomainsRoute,
  ProductsNewRoute: ProductsNewRoute,
  ProductsRequestsRoute: ProductsRequestsRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteRouteWithChildren = ProductsRouteRoute._addFileChildren(
  ProductsRouteRouteChildren,
)

interface PurviewRouteRouteChildren {
  PurviewDataProductsRoute: typeof PurviewDataProductsRoute
  PurviewDefinitionsRoute: typeof PurviewDefinitionsRoute
  PurviewPushRoute: typeof PurviewPushRoute
}

const PurviewRouteRouteChildren: PurviewRouteRouteChildren = {
  PurviewDataProductsRoute: PurviewDataProductsRoute,
  PurviewDefinitionsRoute: PurviewDefinitionsRoute,
  PurviewPushRoute: PurviewPushRoute,
}

const PurviewRouteRouteWithChildren = PurviewRouteRoute._addFileChildren(
  PurviewRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphRouteRoute: GraphRouteRouteWithChildren,
  LineageRouteRoute: LineageRouteRouteWithChildren,
  ProductsRouteRoute: ProductsRouteRouteWithChildren,
  PurviewRouteRoute: PurviewRouteRouteWithChildren,
  ModelSplatRoute: ModelSplatRoute,
  ModelIndexRoute: ModelIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
