/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FabricRouteRouteImport } from './routes/fabric/route'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as ProductsRouteRouteImport } from './routes/products/route'
import { Route as FabricExploreRouteImport } from './routes/fabric/explore'
import { Route as FabricOverviewRouteImport } from './routes/fabric/overview'
import { Route as ModelModelIdRouteImport } from './routes/model.$modelId'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ProductsDomainsRouteImport } from './routes/products/domains'
import { Route as ProductsNewRouteImport } from './routes/products/new'
import { Route as ProductsRequestsRouteImport } from './routes/products/requests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricRouteRoute = FabricRouteRouteImport.update({
  id: '/fabric',
  path: '/fabric',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRouteRoute = ProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricExploreRoute = FabricExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => FabricRouteRoute,
} as any)
const FabricOverviewRoute = FabricOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => FabricRouteRoute,
} as any)
const ModelModelIdRoute = ModelModelIdRouteImport.update({
  id: '/model/$modelId',
  path: '/model/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ProductsDomainsRoute = ProductsDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ProductsRequestsRoute = ProductsRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => ProductsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fabric': typeof FabricRouteRouteWithChildren
  '/products': typeof ProductsRouteRouteWithChildren
  '/models': typeof ModelsRoute
  '/fabric/explore': typeof FabricExploreRoute
  '/fabric/overview': typeof FabricOverviewRoute
  '/model/$modelId': typeof ModelModelIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/domains': typeof ProductsDomainsRoute
  '/products/new': typeof ProductsNewRoute
  '/products/requests': typeof ProductsRequestsRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fabric': typeof FabricRouteRouteWithChildren
  '/models': typeof ModelsRoute
  '/fabric/explore': typeof FabricExploreRoute
  '/fabric/overview': typeof FabricOverviewRoute
  '/model/$modelId': typeof ModelModelIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/domains': typeof ProductsDomainsRoute
  '/products/new': typeof ProductsNewRoute
  '/products/requests': typeof ProductsRequestsRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fabric': typeof FabricRouteRouteWithChildren
  '/products': typeof ProductsRouteRouteWithChildren
  '/models': typeof ModelsRoute
  '/fabric/explore': typeof FabricExploreRoute
  '/fabric/overview': typeof FabricOverviewRoute
  '/model/$modelId': typeof ModelModelIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/domains': typeof ProductsDomainsRoute
  '/products/new': typeof ProductsNewRoute
  '/products/requests': typeof ProductsRequestsRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fabric'
    | '/products'
    | '/models'
    | '/fabric/explore'
    | '/fabric/overview'
    | '/model/$modelId'
    | '/products/$productId'
    | '/products/domains'
    | '/products/new'
    | '/products/requests'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fabric'
    | '/models'
    | '/fabric/explore'
    | '/fabric/overview'
    | '/model/$modelId'
    | '/products/$productId'
    | '/products/domains'
    | '/products/new'
    | '/products/requests'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/fabric'
    | '/products'
    | '/models'
    | '/fabric/explore'
    | '/fabric/overview'
    | '/model/$modelId'
    | '/products/$productId'
    | '/products/domains'
    | '/products/new'
    | '/products/requests'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FabricRouteRoute: typeof FabricRouteRouteWithChildren
  ProductsRouteRoute: typeof ProductsRouteRouteWithChildren
  ModelsRoute: typeof ModelsRoute
  ModelModelIdRoute: typeof ModelModelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabric': {
      id: '/fabric'
      path: '/fabric'
      fullPath: '/fabric'
      preLoaderRoute: typeof FabricRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabric/explore': {
      id: '/fabric/explore'
      path: '/explore'
      fullPath: '/fabric/explore'
      preLoaderRoute: typeof FabricExploreRouteImport
      parentRoute: typeof FabricRouteRoute
    }
    '/fabric/overview': {
      id: '/fabric/overview'
      path: '/overview'
      fullPath: '/fabric/overview'
      preLoaderRoute: typeof FabricOverviewRouteImport
      parentRoute: typeof FabricRouteRoute
    }
    '/model/$modelId': {
      id: '/model/$modelId'
      path: '/model/$modelId'
      fullPath: '/model/$modelId'
      preLoaderRoute: typeof ModelModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/products/domains': {
      id: '/products/domains'
      path: '/domains'
      fullPath: '/products/domains'
      preLoaderRoute: typeof ProductsDomainsRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/products/new': {
      id: '/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/products/requests': {
      id: '/products/requests'
      path: '/requests'
      fullPath: '/products/requests'
      preLoaderRoute: typeof ProductsRequestsRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
  }
}

interface FabricRouteRouteChildren {
  FabricExploreRoute: typeof FabricExploreRoute
  FabricOverviewRoute: typeof FabricOverviewRoute
}

const FabricRouteRouteChildren: FabricRouteRouteChildren = {
  FabricExploreRoute: FabricExploreRoute,
  FabricOverviewRoute: FabricOverviewRoute,
}

const FabricRouteRouteWithChildren = FabricRouteRoute._addFileChildren(
  FabricRouteRouteChildren,
)

interface ProductsRouteRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsDomainsRoute: typeof ProductsDomainsRoute
  ProductsNewRoute: typeof ProductsNewRoute
  ProductsRequestsRoute: typeof ProductsRequestsRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteRouteChildren: ProductsRouteRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsDomainsRoute: ProductsDomainsRoute,
  ProductsNewRoute: ProductsNewRoute,
  ProductsRequestsRoute: ProductsRequestsRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteRouteWithChildren = ProductsRouteRoute._addFileChildren(
  ProductsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FabricRouteRoute: FabricRouteRouteWithChildren,
  ProductsRouteRoute: ProductsRouteRouteWithChildren,
  ModelsRoute: ModelsRoute,
  ModelModelIdRoute: ModelModelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
